"""Initial migration

Revision ID: 2e71d7540a6a
Revises: 
Create Date: 2026-07-23 20:13:27.589889

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e71d7540a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxons_id'), 'taxons', ['id'], unique=False)
    op.create_index(op.f('ix_taxons_parent_id'), 'taxons', ['parent_id'], unique=False)
    op.create_index(op.f('ix_taxons_rank'), 'taxons', ['rank'], unique=False)
    op.create_index(op.f('ix_taxons_scientific_name'), 'taxons', ['scientific_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxons_scientific_name'), table_name='taxons')
    op.drop_index(op.f('ix_taxons_rank'), table_name='taxons')
    op.drop_index(op.f('ix_taxons_parent_id'), table_name='taxons')
    op.drop_index(op.f('ix_taxons_id'), table_name='taxons')
    op.drop_table('taxons')
    # ### end Alembic commands ###
